---
# tasks file for role-clusterpi

# Ensure dirs
- name: Ensure dir for output images
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ stage_dir }}/"
    - "{{ stage_dir }}/{{ cluster_nodenumber_item }}"
    - "{{ stage_dir }}/{{ cluster_nodenumber_item }}/boot"
    - "{{ stage_dir }}/{{ cluster_nodenumber_item }}/boot/firmware"
    - "{{ stage_dir }}/{{ cluster_nodenumber_item }}/root"

# Place all files
- name: Place all file
  ansible.builtin.copy:
    src: "{{ item.name }}"
    dest: "{{ stage_dir }}/{{ cluster_nodenumber_item }}/{{ item.dest }}"
    mode: 0755
  when: item.type == "file"
  loop: "{{ prepare_image_files }}"

- debug:
    msg: "{{ cluster_name }}{{ '%02d' % cluster_nodenumber_item | int }}"

# Place all templates
- name: Place all template
  ansible.builtin.template:
    src: "{{ item.name }}"
    dest: "{{ stage_dir }}/{{ cluster_nodenumber_item }}/{{ item.dest }}"
    mode: 0755
  when: item.type == "template"
  loop: "{{ prepare_image_files }}"

- name: Create packer json specifier
  ansible.builtin.template:
    src: "packer-builder-arm/{{ pios64_image.packer_template }}"
    dest: "{{ stage_dir }}/{{ cluster_nodenumber_item }}/{{ pios64_image.packer_template | replace('.j2','') }}"
    mode: '0644'