---
# tasks file for role-clusterpi

# Load needed environment vars (please create your own)
- name: Load "{{ cluster_environment }}" needed vars
  include_vars: "{{ cluster_environment }}.yml"
  when:
  - cluster_environment is defined   

# Place all files in staging area
- name: Copy file and templates
  include_tasks: prepare_images/copy_files.yml
  with_sequence: count="{{ cluster_nodenumber | int }}"
  loop_control:
    loop_var: cluster_nodenumber_item
