---
# Playbook for node img preparation

- hosts: localhost
  vars:
    cluster_nodenumber: 3 
    
  tasks:
  - name: loop
    debug:
      msg: "{{ '%02d' % cluster_nodenumber_item | int }}"
    with_sequence: count="{{ cluster_nodenumber | int }}"
    loop_control:
      loop_var: cluster_nodenumber_item
