---
# tasks file for role-prep_pi_images

# Load needed environment vars (please create your own)
- name: Load "{{ cluster_environment }}" needed vars
  include_vars: "{{ cluster_environment }}.yml"

- name: Create destination
  copy:
    src: "images/in/hypriotos-rpi-v{{ hypriot_version }}.img"
    dest: "images/out/{{ cluster_name }}{{ '%02d' % item | int }}.img"
    owner: root
    group: root
    mode: '0755'
  with_sequence: count="{{ cluster_nodenumber | int }}"

- name: Enforce mountpoint
  file:
    path: "{{ hypriot_isomount }}/{{ item.name }}"
    state: directory
    mode: '0755'
  loop: "{{ hypriot_partitions }}"

- name: Create loop devices
  command:
    argv:
      - losetup
      - --show
      - -f
      - -P
      - "images/out/{{ cluster_name }}{{ '%02d' % item | int }}.img"
  with_sequence: count="{{ cluster_nodenumber | int }}"
  register: loop_devices

- debug:
    var: results

- set_fact:
    loop_device: "{{ loop_devices.results[0].stdout }}"

- debug:
    var: loop_device

- name: Mount loop devices
  mount:
    path: "{{ hypriot_isomount }}/{{ item.name }}"
    src: "{{ loop_device }}{{ item.pname }}"
    fstype: "{{ item.fstype }}"
    opts: "{{ item.fsopts }}"
    state: present
  loop: "{{ hypriot_partitions }}"

# Remove automating partitioning at all (if not requested)
- name: cmdline.txt (raspberry first boot)
  debug:
    msg: "ToDo"

- name: /etc/cloud/cloud.cfg (cloud-init)
  debug:
    msg: "ToDo"

# Disable wifi and bluetooth (if not requested)
- name: config.txt (raspberry first boot)
  debug:
    msg: "ToDo"

- name: user-data (cloud-init)
  debug:
    msg: "ToDo"

- name: Interface configuration (cloud-init)
  debug:
    msg: "ToDo"

- name: Resolver (cloud-init)
  debug:
    msg: "ToDo"

- name: Umount loop devices
  mount:
    path: "{{ hypriot_isomount }}/{{ item.name }}"
    src: "{{ loop_device }}{{ item.pname }}"
    state: absent
  loop: "{{ hypriot_partitions }}"

- name: Destroy loop device
  command:
    argv:
      - losetup
      - -d
      - "{{ loop_device }}"
